#!/usr/bin/env node
/**
 * store.mjs — distilled memory notes -> RAGFlow dataset
 *
 * Part 3 of the DSH memory pipeline.
 *
 * GRANULARITY
 *   One RAGFlow document PER TURN, not per session. A session document would be
 *   chunked blind across unrelated turns and would have to be re-uploaded whole
 *   every time the session grows; per-turn documents keep retrieval precise and
 *   make ingestion incremental.
 *
 * DOCUMENT NAMING (idempotency key)
 *   <yyyy-mm-dd>--<project-slug>--<sessionId>--turn<NN>.md
 *   Re-running replaces the same turn instead of duplicating it.
 *
 * FLOW
 *   1. (optionally) create/find the dataset
 *   2. upload each turn document
 *   3. trigger parsing and poll until each document is DONE/FAILED
 *   4. optionally run a retrieval probe to prove the loop closes
 *
 * Usage:
 *   node store.mjs --ensure-dataset
 *   node store.mjs --dir <notes-dir> [--probe "query"] [--no-parse]
 *   node store.mjs --dir <notes-dir> --list
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const DSH_HOME = process.env.DSH_HOME ?? path.join(os.homedir(), '.dsh');
const BASE = (process.env.RAGFLOW_BASE_URL ?? 'http://127.0.0.1:19380').replace(/\/+$/, '');
const DATASET_NAME = process.env.MEMORY_DATASET ?? 'dsh-memory';
const EMBEDDING = process.env.MEMORY_EMBEDDING ?? 'qwen3-embedding:8b@Ollama';
const STATE_FILE = path.join(process.cwd(), '.dataset-id');

// ------------------------------------------------------------------ secrets

function apiKey() {
  if (process.env.RAGFLOW_API_KEY) return process.env.RAGFLOW_API_KEY;
  const envFile = path.join(DSH_HOME, '.env');
  if (fs.existsSync(envFile)) {
    for (const l of fs.readFileSync(envFile, 'utf8').split(/\r?\n/)) {
      const m = /^\s*RAGFLOW_API_KEY\s*=\s*(\S+)\s*$/.exec(l);
      if (m) return m[1];
    }
  }
  return null;
}

// --------------------------------------------------------------------- http

function makeClient(key) {
  const headers = { Authorization: `Bearer ${key}` };
  const jheaders = { ...headers, 'Content-Type': 'application/json' };

  const json = async (method, ep, body, timeoutMs = 120000) => {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), timeoutMs);
    try {
      const res = await fetch(`${BASE}${ep}`, {
        method,
        headers: jheaders,
        body: body === undefined ? undefined : JSON.stringify(body),
        signal: ctl.signal,
      });
      const text = await res.text();
      let j;
      try {
        j = JSON.parse(text);
      } catch {
        throw new Error(`${method} ${ep} -> non-JSON (HTTP ${res.status}): ${text.slice(0, 200)}`);
      }
      if (j.code !== 0) throw new Error(`${method} ${ep} -> code=${j.code} ${j.message ?? ''}`);
      return j.data;
    } finally {
      clearTimeout(t);
    }
  };

  const upload = async (dataset, name, content, timeoutMs = 180000) => {
    const fd = new FormData();
    fd.append('file', new Blob([content], { type: 'text/markdown' }), name);
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), timeoutMs);
    try {
      const res = await fetch(`${BASE}/api/v1/datasets/${dataset}/documents`, {
        method: 'POST',
        headers, // let fetch set the multipart boundary
        body: fd,
        signal: ctl.signal,
      });
      const text = await res.text();
      let j;
      try {
        j = JSON.parse(text);
      } catch {
        throw new Error(`upload -> non-JSON (HTTP ${res.status}): ${text.slice(0, 200)}`);
      }
      if (j.code !== 0) throw new Error(`upload -> code=${j.code} ${j.message ?? ''}`);
      return j.data;
    } finally {
      clearTimeout(t);
    }
  };

  return { json, upload };
}

// --------------------------------------------------------------- operations

async function findOrCreateDataset(c, create) {
  const list = await c.json('GET', `/api/v1/datasets?name=${encodeURIComponent(DATASET_NAME)}`);
  const hit = (list ?? []).find((d) => d.name === DATASET_NAME);
  if (hit) return hit;
  if (!create) throw new Error(`dataset "${DATASET_NAME}" not found (run with --ensure-dataset)`);
  const made = await c.json('POST', '/api/v1/datasets', {
    name: DATASET_NAME,
    description: 'DSH cross-session memory (generated by memory-bridge)',
    embedding_model: EMBEDDING,
    chunk_method: 'naive',
    parser_config: { chunk_token_num: 512, delimiter: '\n', layout_recognize: 'Plain Text' },
  });
  return made;
}

/** Split a session markdown document into per-turn documents. */
function splitTurns(markdown) {
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(markdown);
  const front = m ? m[1] : '';
  const body = m ? m[2] : markdown;

  const fm = {};
  for (const line of front.split('\n')) {
    const mm = /^(\w+):\s*(.*)$/.exec(line.trim());
    if (mm) fm[mm[1]] = mm[2].replace(/^"|"$/g, '');
  }

  // Split BEFORE each "### " heading. Splitting on "---" first does not work:
  // the synthesized document always starts with an "# H1" title, so the first
  // section never begins with "###" and every turn would be dropped.
  const sections = body
    .split(/\r?\n(?=###\s)/)
    .map((s) => s.trim())
    .filter((s) => s.includes('###'));

  return sections.map((sec, i) => {
    const headingLine = sec.split(/\r?\n/).find((l) => l.startsWith('###')) ?? '';
    const title = headingLine.replace(/^###\s*/, '').trim();
    return { index: i + 1, title, section: sec, front: fm };
  });
}

function docName(fm, turnIndex, title) {
  const date = fm.date ?? 'unknown-date';
  const project = (fm.project ?? 'unknown')
    .replace(/^[A-Za-z]:\\?/, '')
    .replace(/[\\/]+/g, '-')
    .replace(/[^A-Za-z0-9\u4e00-\u9fa5._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40) || 'unknown';
  const sid = (fm.session ?? 'nosession').replace(/[^A-Za-z0-9-]/g, '');
  const slug = title.replace(/[\\/:*?"<>|\n\r]+/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 60);
  return `${date}--${project}--${sid}--turn${String(turnIndex).padStart(2, '0')}--${slug}.md`;
}

function docBody(t, fm) {
  return [
    '---',
    `project: ${JSON.stringify(fm.project ?? '')}`,
    `session: ${fm.session ?? ''}`,
    `date: ${fm.date ?? ''}`,
    `turn: ${t.index}`,
    `source: ${fm.source ?? 'dsh-session'}`,
    '---',
    '',
    t.section,
    '',
  ].join('\n');
}

async function pollParse(c, dataset, docIds, timeoutMs = 20 * 60 * 1000) {
  const deadline = Date.now() + timeoutMs;
  const pending = new Set(docIds);
  const done = {};
  let announced = false;
  while (pending.size > 0 && Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, 4000));
    const list = await c.json(
      'GET',
      `/api/v1/datasets/${dataset}/documents?page=1&page_size=100`,
    );
    const docs = list?.docs ?? list ?? [];
    for (const d of docs) {
      if (!pending.has(d.id)) continue;
      const st = d.run ?? d.status ?? '?';
      if (st === '3' || st === 'DONE' || st === '1' || st === 'FAIL' || d.progress === 1 || d.progress === -1) {
        done[d.id] = { name: d.name, run: st, progress: d.progress, chunks: d.chunk_count };
        pending.delete(d.id);
      }
    }
    if (!announced && pending.size > 0) {
      process.stdout.write(`    parsing... ${pending.size} pending\n`);
      announced = true;
    }
  }
  return { done, stillPending: [...pending] };
}

// ---------------------------------------------------------------------- cli

async function main() {
  const argv = process.argv.slice(2);
  const arg = (k, def = null) => {
    const i = argv.indexOf(k);
    return i >= 0 && i + 1 < argv.length ? argv[i + 1] : def;
  };
  const has = (k) => argv.includes(k);

  const key = apiKey();
  if (!key) {
    console.error('RAGFLOW_API_KEY not found (env or $DSH_HOME/.env)');
    process.exit(2);
  }
  const c = makeClient(key);
  console.log(`ragflow : ${BASE}`);
  console.log(`dataset : ${DATASET_NAME}   embedding=${EMBEDDING}\n`);

  // --ensure-dataset
  const ds = await findOrCreateDataset(c, true);
  fs.writeFileSync(STATE_FILE, ds.id, 'utf8');
  console.log(`dataset id : ${ds.id}`);
  console.log(`existing   : docs=${ds.document_count ?? 0} chunks=${ds.chunk_count ?? 0}\n`);

  if (has('--list')) {
    const list = await c.json('GET', `/api/v1/datasets/${ds.id}/documents?page=1&page_size=100`);
    const docs = list?.docs ?? list ?? [];
    console.log(`documents (${docs.length}):`);
    for (const d of docs.slice(0, 40)) {
      console.log(`  [run=${d.run ?? d.status}] chunks=${d.chunk_count ?? '?'}  ${d.name}`);
    }
    if (docs.length > 40) console.log(`  ... +${docs.length - 40} more`);
    return;
  }

  const dir = arg('--dir');
  if (!dir) {
    console.log('Provide --dir <notes-dir> to ingest, or --list to inspect.');
    return;
  }
  if (!fs.existsSync(dir)) {
    console.error(`dir not found: ${dir}`);
    process.exit(3);
  }

  // Recurse: distilled notes live under <dir>/<project-slug>/*.md
  const files = [];
  (function walk(d) {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith('.md')) files.push(p);
    }
  })(dir);

  console.log(`markdown docs found: ${files.length}`);
  if (files.length === 0) return;

  const uploaded = [];
  for (const full of files) {
    const f = path.relative(dir, full);
    const md = fs.readFileSync(full, 'utf8');
    const turns = splitTurns(md);
    console.log(`\n${f}: ${turns.length} turn(s)`);
    for (const t of turns) {
      const name = docName(t.front, t.index, t.title);
      try {
        const r = await c.upload(ds.id, name, docBody(t, t.front));
        const id = Array.isArray(r) ? r[0]?.id : r?.id;
        uploaded.push({ id, name });
        console.log(`  + ${name}`);
      } catch (e) {
        console.log(`  ! ${name} -> ${e.message}`);
      }
    }
  }

  console.log(`\nuploaded ${uploaded.length} document(s)`);

  if (!has('--no-parse') && uploaded.length > 0) {
    const ids = uploaded.map((u) => u.id).filter(Boolean);
    console.log('\ntriggering parse...');
    try {
      await c.json('POST', `/api/v1/datasets/${ds.id}/chunks`, { document_ids: ids });
      console.log('parse triggered; polling for completion');
      const { done, stillPending } = await pollParse(c, ds.id, ids);
      const finished = Object.values(done);
      console.log(`\nparsed: ${finished.length} finished, ${stillPending.length} still pending`);
      let chunks = 0;
      for (const d of finished) {
        chunks += d.chunks ?? 0;
      }
      console.log(`chunks created (reported): ${chunks}`);
      const failed = finished.filter((d) => d.progress === -1 || d.run === 'FAIL' || d.run === '1');
      if (failed.length) {
        console.log('FAILED documents:');
        failed.forEach((d) => console.log(`  ${d.name}`));
      }
    } catch (e) {
      console.log(`parse trigger failed: ${e.message}`);
    }
  }

  const probe = arg('--probe');
  if (probe) {
    console.log(`\nretrieval probe: "${probe}"`);
    const r = await c.json('POST', '/api/v1/retrieval', {
      question: probe,
      dataset_ids: [ds.id],
      page_size: 5,
      similarity_threshold: 0.2,
      vector_similarity_weight: 0.3,
    });
    const chunks = r?.chunks ?? [];
    console.log(`  hits: ${chunks.length}`);
    for (const ch of chunks.slice(0, 5)) {
      const txt = (ch.content ?? '').replace(/\s+/g, ' ').slice(0, 180);
      console.log(`  [${(ch.similarity ?? 0).toFixed(3)}] ${txt}`);
    }
  }
}

main().catch((e) => {
  console.error('FATAL: ' + e.message);
  process.exit(1);
});

